### ISSUE TITLE
re-visit git_forking.md article

### ISSUE THREAD

**Issue by aaronkyle** [src-its/ca-web#14]
Both @fkast and @sorayaweill created articles about forking in Git.  I merged those two drafts into a single file:

https://github.com/src-its/ca-web/blob/master/content/git_forking.md

Both of the original articles, however, are still presented as stand-alone documents.  These two drafts need to be merged together into a single article.

Also: It is _very_ important to keep track of the reference materials used when you are composing articles.  Go back and add citations.

**Comment by fkast** [comment]
Soraya's were basically small grammer and sentence edits to mine, so I only left her copy. I didn't do any references, because I typed the article based on my experience with forks.
