### ISSUE TITLE
content: git_forking.md: Content describes GitHub and not Git.

### ISSUE THREAD

**Issue by barracks510** [src-its/ca-web#15]
Page is vendor specific, and therefore the generalizations in the text of the article are inaccurate. Forking is a split in the software development process where another team or individual begins to take the project in a different direction than originally intended. [See here](https://en.wikipedia.org/wiki/Fork_%28software_development%29). Forking has nothing to do with Git or Github. 

Traditional Git work flows for the type of activity described in the content of the article do not revolve around pull requests and forks. In fact, as Git is a distributed version control system, and GitHub's code contribution method is very centralized, the original users and creators of Git (the Linux kernel team) see this new method as an abomination of Git as a useful piece of software. As you may see, some members of the kernel community and more are very passionate about this issue. See this [from the creator himself, Linus Torvalds](https://github.com/torvalds/linux/pull/17), and also [from the most popular Git service, Gitolite](https://github.com/sitaramc/gitolite/wiki). Of course, the monopoly of Github has forced all but the most incorruptible purists to adopt this moronic work flow. It's not the first time _hipsters_ really f**ked things over.

**Comment by aaronkyle** [comment]
This is a very good clarification.  Please either contribute clarifications directly or otherwise assign a person to do so.

**Comment by aaronkyle** [comment]
@fkast : Per Dennis' suggestion, it'd be appropriate to rename / move this article from git_forking.md to github_forking.md
