### ISSUE TITLE
add your schedule details to our spreadsheet

### ISSUE THREAD

**Issue by aaronkyle** [src-its/ca-web#2]
Be sure to add your availability to our schedule so that we can finalize CA shift assignments:

https://docs.google.com/spreadsheets/d/1H0jP2IAAVYsJbwoueqLuI8sPf21ow3XJjSlMxTiXOGA/edit

**Comment by fkast** [comment]
Sorry it took so long. I have a pretty busy schedule as you can see, so I had to find the right times I am actually available to work.
