### ISSUE TITLE
Images for article

### ISSUE THREAD

**Issue by sorayaweill** [src-its/ca-web#5]
I really don't understand how you save an image on a specific content page for an article.

**Comment by aaronkyle** [comment]
The code for adding an image is `![]()` . The `!` tells Markdown that you will be linking an image.  The first brackets `[]` are used to name the image.  The final parenthesis `()` link to the image file.

Thus, to show a photo of a constellation, I would write this:

`![How To Find Hydra, The Largest Constellation In The Sky](http://i2.wp.com/astrobob.areavoices.com/files/2015/03/Hydra-water-snake-constellation.jpg)`

The output is auto-formatted for any article with a `.md` markdown extension:

![How To Find Hydra, The Largest Constellation In The Sky](http://i2.wp.com/astrobob.areavoices.com/files/2015/03/Hydra-water-snake-constellation.jpg)
